package address

import "github.com/iotaledger/goshimmer/packages/model/ledger/balance"

const (
	MARSHALED_ENTRY_HISTORY_COUNT_START = 0
	MARSHALED_ENTRY_ADDRESS_START       = MARSHALED_ENTRY_HISTORY_COUNT_END
	MARSHALED_ENTRY_SHARD_START         = MARSHALED_ENTRY_ADDRESS_END
	MARSHALED_ENTRY_ACCUMULATED_START   = MARSHALED_ENTRY_SHARD_END
	MARSHALED_ENTRY_HISTORY_START       = MARSHALED_ENTRY_ACCUMULATED_END

	MARSHALED_ENTRY_HISTORY_COUNT_END = MARSHALED_ENTRY_HISTORY_COUNT_START + MARSHALED_ENTRY_HISTORY_COUNT_SIZE
	MARSHALED_ENTRY_ADDRESS_END       = MARSHALED_ENTRY_ADDRESS_START + MARSHALED_ENTRY_ADDRESS_SIZE
	MARSHALED_ENTRY_SHARD_END         = MARSHALED_ENTRY_SHARD_START + MARSHALED_ENTRY_SHARD_SIZE
	MARSHALED_ENTRY_ACCUMULATED_END   = MARSHALED_ENTRY_ACCUMULATED_START + MARSHALED_ENTRY_ACCUMULATED_SIZE

	MARSHALED_ENTRY_HISTORY_COUNT_SIZE = 8
	MARSHALED_ENTRY_ADDRESS_SIZE       = 243
	MARSHALED_ENTRY_SHARD_SIZE         = 11
	MARSHALED_ENTRY_ACCUMULATED_SIZE   = 8
	MARSHALED_BALANCE_ENTRY_SIZE       = balance.MARSHALED_ENTRY_VALUE_SIZE + balance.MARSHALED_ENTRY_TIMESTAMP_SIZE
	MARSHALED_ENTRY_MIN_SIZE           = MARSHALED_ENTRY_HISTORY_COUNT_SIZE + MARSHALED_ENTRY_ADDRESS_SIZE + MARSHALED_ENTRY_SHARD_SIZE + MARSHALED_ENTRY_ACCUMULATED_SIZE
)
