package balance

const (
	MARSHALED_ENTRY_VALUE_START     = 0
	MARSHALED_ENTRY_TIMESTAMP_START = MARSHALED_ENTRY_VALUE_END

	MARSHALED_ENTRY_VALUE_END     = MARSHALED_ENTRY_VALUE_START + MARSHALED_ENTRY_VALUE_SIZE
	MARSHALED_ENTRY_TIMESTAMP_END = MARSHALED_ENTRY_TIMESTAMP_START + MARSHALED_ENTRY_TIMESTAMP_SIZE

	MARSHALED_ENTRY_VALUE_SIZE     = 8
	MARSHALED_ENTRY_TIMESTAMP_SIZE = 8
)
